name: fruit_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  achievement_view: ^1.0.1
  animate_do: ^4.2.0
  cloud_firestore: ^5.6.9
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_facebook_auth: ^7.1.2
  flutter_localization: ^0.3.2
  flutter_paypal_payment: ^1.0.8
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.3
  google_sign_in: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
  package_info_plus: ^8.3.0
  restart_app: ^1.3.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.0
  svg_flutter: ^0.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - langs/
    - assets/images/vuesax/bold/
    - assets/images/vuesax/outline/
  fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/app_icon_.png
#   branding: assets/images/branding_white.png
#   color_dark: "#000000"
#   image_dark: assets/images/app_icon_.png
#   branding_dark: assets/images/branding_black.png
#   android_12:
#     image: assets/images/app_icon_.png
#     icon_background_color: "#ffffff"
#     image_dark: assets/images/app_icon_.png
#     icon_background_color_dark: "#000000"
# # flutter pub run flutter_native_splash:create
# # flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_icon_.png"
  image_path_ios: "assets/images/app_icon_.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon_.png"

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/styles/images/
  filename: app_images.dart
  classname: Assets
  field_prefix:
    from: assetsImages
    to: images
